---

- name: Current pwd
  command: pwd

- name: Node & Npm versions 
  command: chdir={{ DIR }} node -v && npm -v

- name: Run npm install
  command: chdir={{ DIR }} npm install

- name: Run npm build
  command: chdir={{ DIR }} npm run build --prod