---

# - name: Create site backup
  # command: chdir={{ DIR }} php artisan backup:run

- name: Run composer install
  command: chdir={{ DIR }} composer install --no-dev

- name: Maintainance mode
  command: chdir={{ DIR }} php artisan down

- name: link assets folder
  command: php artisan storage:link

- name: Clear the cache
  command: chdir={{ DIR }} php artisan config:cache

- name: Artisan migrate
  command: chdir={{ DIR }} php artisan migrate

- name: End Maintainance mode
  command: chdir={{ DIR }} php artisan up
