---

# - name: Create site backup
  # command: chdir={{ DIR }} php artisan backup:run

- name: Run composer install
  command: chdir={{ DIR }} composer install --no-dev

- name: Maintainance mode
  command: chdir={{ DIR }} php artisan down

- name: Clear the cache
  command: chdir={{ DIR }} php artisan config:cache

- name: Node & Npm versions 
  command: chdir={{ DIR }} node -v && npm -v

- name: Run npm install
  command: chdir={{ DIR }} npm install

- name: Run npm build
  command: chdir={{ DIR }} npm run build --prod

- name: Artisan migrate
  command: chdir={{ DIR }} php artisan migrate

- name: End Maintainance mode
  command: chdir={{ DIR }} php artisan up
