---
- name: copy files
  synchronize: # Rsync
    src: "../../../"
    dest: "{{ lookup('env', 'PATH_TO_ROOT') }}"
    delete: no
    perms: no # Don't use perm/owner/group from the build server as this is all root/root/777.
    owner: no # TODO: test to see that this is true and fix if possible.
    group: no
    recursive: yes
    rsync_opts:
      - "--exclude-from={{ lookup('env', 'PROD_SYNC_EXCLUDE_LIST') }}"