image: renato1976/rnt-ansible:0.17

stages:
  - test
  - deploy

test_code:
  stage: test
  script:
    - echo "testing .."
    - pwd
    - composer update --lock
    - composer install
    - composer phpstan

# Deploy to Production
deploy_production:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PROD_PRIVATE" | ssh-add -
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  stage: deploy
  tags:
    - Docker
  when: manual
  environment:
    name: Production
  script:
    - npm -v
    - node -v
    - npm install 
    - npm run build

    - chmod 600 ./gitlab/ansible
    - cd ./gitlab/ansible
    - ansible -i inventory.yml prod -m ping -vvv
    - ansible-playbook -i inventory.yml prod-deploy.yml --limit=prod
  only:
    - main
