prod:
  hosts:
    prod:
      ansible_ssh_user: "{{ lookup('env','ANSIBLE_USER') }}"
      ansible_host: "{{ lookup('env','ANSIBLE_HOST_IP') }}"
      ansible_ssh_private_key_file: "{{ lookup('env','SSH_PROD_PRIVATE') }}"
      # ansible_pass: yooo 